name: build

on:
  release:
    types:
      - created

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          prefix: poker-odds
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
          tag_name: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
